int a = 25;
int b = 12;
int c = 125;
int d = 76;
int e = 111;
int max  = a;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.WriteLine(max);